import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <title>Hello Edison</title>
      <meta name="keywords" content='网站开发,Next.js,javascriptsss'></meta>
      <body className={inter.className}>


        <Link href={'/users'}>Users</Link>
        <Link href={'/about'} >Aboutssss</Link>

        {children}</body>
    </html>
  )
}
